### ISSUE TITLE
可以增加name的翻译输出，以及不翻译重复文本的功能吗。

### ISSUE THREAD

**Issue by wjh191** [GalTransl/GalTransl#73]
1、类似翻译人名到name_zh这样，如果有人不想翻译人名可以弄个开关功能。目前是通过译后词典替换的，但人名一多感觉好累。

2、有些游戏不同路线的文本是一样，如果都翻的话有点浪费。比如上下文相同的文本超过3行这种情况可以不用翻译，使用已经翻译过的结果，应该不会影响翻译质量，同时可以减少消费。

**Comment by cx2333-gt** [comment]
让gpt翻译name目前不在考虑范围内，因为会出现有的翻译有的不翻译的现象。其实有比较快的弄法，以后写出来。
